export const NotParamMsg = '喵呜~ 参数好像不太对呢'
export const NotOrgParamMsg = '喵呜~ 组织名不能为空'
export const NotUserParamMsg = '喵呜~ 用户名不能为空'
export const NotRepoParamMsg = '喵呜~ 仓库名不能为空'
export const NotOrgOrUserParamMsg = '喵呜~ 组织名或用户名不能为空'
export const NotOrgOrRepoParamMsg = '喵呜~ 组织名或仓库名不能为空'

export const NotPerrmissionMsg = '喵呜~ 访问被拒绝啦，可能是令牌过期了'
export const NotOrgMsg = '喵呜~ 这个组织不存在哦'
export const NotRepoMsg = '喵呜~ 这个仓库不存在哦'
export const NotOrgOrRepoMsg = '喵呜~ 这个组织或仓库不存在哦'
export const NotUserMsg = '喵呜~ 这个用户不存在哦'
export const NotOrgOrUserMsg = '喵呜~ 这个组织或用户不存在哦'
export const NotCommitMsg = '喵呜~ 这个提交不存在哦'
export const NotCommitOrRepoMsg = '喵呜~ 这个提交或仓库不存在哦'
export const NotIssueMsg = '喵呜~ 这个问题不存在哦'
export const NotBranchMsg = '喵呜~ 这个分支不存在哦'
export const NotTagMsg = '喵呜~ 这个标签不存在哦'
export const NotProxyAddressMsg = '喵呜~ 代理地址格式不正确哦'

export const isOrgMsg = '喵呜~ 组织账号暂不支持'
export const isNotTokenMsg = '喵呜~ 这个令牌似乎不是有效的'
