export const NotParamMsg = '喵呜~ 参数好像不太对呢'
export const NotUrlParamMsg = '喵呜~ 仓库URL不能为空'
export const NotOwnerParamMsg = '喵呜~ 仓库拥有者不能为空'
export const NotOwnerOrRepoParamMsg = '喵呜~ 仓库拥有者或仓库名不能为空'
export const NotOrgParamMsg = '喵呜~ 组织名不能为空'
export const NotUserParamMsg = '喵呜~ 用户名不能为空'
export const NotUserIdParamMsg = '喵呜~ 用户ID不能为空'
export const NotRepoParamMsg = '喵呜~ 仓库名不能为空'
export const NotOrgOrUserParamMsg = '喵呜~ 组织名或用户名不能为空'
export const NotOrgOrRepoParamMsg = '喵呜~ 组织名或仓库名不能为空'
export const NotProxyAddressMsg = '喵呜~ 代理地址格式不正确哦'
export const NotRefreshTokenSuccessMsg = '喵呜~ 访问令牌刷新失败'
export const NotAccessTokenMsg = '喵呜~ 访问令牌不能为空'
export const NotRefreshTokenMsg = '喵呜~ 刷新令牌不能为空'
export const NotAccessCodeMsg = '喵呜~ 授权码不能为空'

export const NotPerrmissionMsg = '喵呜~ 访问被拒绝啦，可能是令牌过期了或权限不足'
export const NotOrgMsg = '喵呜~ 这个组织不存在哦'
export const NotRepoMsg = '喵呜~ 这个仓库不存在哦'
export const NotRepoOrPerrmissionMsg = '喵呜~ 这个仓库不存在或访问被拒绝啦，可能是令牌过期了或权限不足'
export const NotOrgOrRepoMsg = '喵呜~ 这个组织或仓库不存在哦'
export const NotUserMsg = '喵呜~ 这个用户不存在哦'
export const NotOrgOrUserMsg = '喵呜~ 这个组织或用户不存在哦'
export const NotCommitMsg = '喵呜~ 这个提交不存在哦'
export const NotCommitOrRepoMsg = '喵呜~ 这个提交或仓库不存在哦'
export const NotIssueMsg = '喵呜~ 这个议题不存在哦'
export const NotIssueNumberMsg = '喵呜~ 这个议题编号不能为空哦'
export const NotIssueCommentNumberMsg = '喵呜~ 这个议题评论编号不能为空哦'
export const NotIssueCommentMsg = '喵呜~ 这个议题评论不存在哦'
export const NotIssueCommentBodyMsg = '喵呜~ 这个议题评论内容不能为空哦'
export const NotIssueBodyMsg = '喵呜~ 这个议题内容不能为空哦'
export const NotIssueTitleMsg = '喵呜~ 议题标题不能为空'
export const NotSubIssueNumberMsg = '喵呜~ 这个子议题编号不能为空哦'
export const NotBranchMsg = '喵呜~ 这个分支不存在哦'
export const NotTagMsg = '喵呜~ 这个标签不存在哦'

export const NotWebHookSignatureMsg = '喵呜~ WebHook 签名验证失败'

export const isNotAccessTokenMsg = '喵呜~ 这个令牌似乎不是有效的'
export const isNotRefreshTokenMsg = '喵呜~ 这个刷新令牌似乎不是有效的'
export const isNotAccessTokeMsg = '喵呜~ 这个令牌似乎不是有效的'
export const isNotSuccessAccessTokenMsg = '喵呜~ 访问令牌已过期'
export const isOrgMsg = '喵呜~ 组织账号暂不支持'
export const isNotWebHookSignatureMsg = '喵呜~ WebHook 签名格式不正确'
export const isNotPerrmissionMsg = '喵呜~ 权限不正确，请检查权限'

export const RateLimitMsg = '喵呜~ 访问速率受限啦 请等待1小时后再试 或 使用访问令牌提升限额'
