export const RefreshAccessTokenSuccessMsg = '喵呜~ 访问令牌刷新成功'
export const AccessTokenSuccessMsg = '喵呜~ 访问令牌有效'
export const WebHookSignatureSuccessMsg = '喵呜~ WebHook 签名成功'
export const IssucLockSuccessMsg = '喵呜~ 议题锁定成功'
export const IssueUnlockSuccessMsg = '喵呜~ 议题解锁成功'
export const IssueCommentCreateSuccessMsg = '喵呜~ 议题评论创建成功'
export const DeleteReleaseSuccessMsg = '喵呜~ 发行版本删除成功'
